// Code generated by MockGen. DO NOT EDIT.
// Source: function_test.go
//
// Generated by this command:
//
//	mockgen -source=function_test.go -destination=./mock/mock_function_test.go
//
// Package mock_service is a generated GoMock package.
package mock_service
