// Code generated by MockGen. DO NOT EDIT.
// Source: function.go
//
// Generated by this command:
//
//	mockgen -source=function.go -destination=./mock/mock_function.go
//
// Package mock_repository is a generated GoMock package.
package mock_repository

import (
	context "context"
	reflect "reflect"

	model "github.com/Aton-Kish/syncup/internal/syncup/domain/model"
	gomock "go.uber.org/mock/gomock"
)

// MockFunctionRepository is a mock of FunctionRepository interface.
type MockFunctionRepository struct {
	ctrl     *gomock.Controller
	recorder *MockFunctionRepositoryMockRecorder
}

// MockFunctionRepositoryMockRecorder is the mock recorder for MockFunctionRepository.
type MockFunctionRepositoryMockRecorder struct {
	mock *MockFunctionRepository
}

// NewMockFunctionRepository creates a new mock instance.
func NewMockFunctionRepository(ctrl *gomock.Controller) *MockFunctionRepository {
	mock := &MockFunctionRepository{ctrl: ctrl}
	mock.recorder = &MockFunctionRepositoryMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockFunctionRepository) EXPECT() *MockFunctionRepositoryMockRecorder {
	return m.recorder
}

// Delete mocks base method.
func (m *MockFunctionRepository) Delete(ctx context.Context, apiID, name string) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Delete", ctx, apiID, name)
	ret0, _ := ret[0].(error)
	return ret0
}

// Delete indicates an expected call of Delete.
func (mr *MockFunctionRepositoryMockRecorder) Delete(ctx, apiID, name any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Delete", reflect.TypeOf((*MockFunctionRepository)(nil).Delete), ctx, apiID, name)
}

// Get mocks base method.
func (m *MockFunctionRepository) Get(ctx context.Context, apiID, name string) (*model.Function, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Get", ctx, apiID, name)
	ret0, _ := ret[0].(*model.Function)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// Get indicates an expected call of Get.
func (mr *MockFunctionRepositoryMockRecorder) Get(ctx, apiID, name any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Get", reflect.TypeOf((*MockFunctionRepository)(nil).Get), ctx, apiID, name)
}

// List mocks base method.
func (m *MockFunctionRepository) List(ctx context.Context, apiID string) ([]model.Function, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "List", ctx, apiID)
	ret0, _ := ret[0].([]model.Function)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// List indicates an expected call of List.
func (mr *MockFunctionRepositoryMockRecorder) List(ctx, apiID any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "List", reflect.TypeOf((*MockFunctionRepository)(nil).List), ctx, apiID)
}

// Save mocks base method.
func (m *MockFunctionRepository) Save(ctx context.Context, apiID string, function *model.Function) (*model.Function, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Save", ctx, apiID, function)
	ret0, _ := ret[0].(*model.Function)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// Save indicates an expected call of Save.
func (mr *MockFunctionRepositoryMockRecorder) Save(ctx, apiID, function any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Save", reflect.TypeOf((*MockFunctionRepository)(nil).Save), ctx, apiID, function)
}
